'use strict';
const {invoke}=window.__TAURI__.core;
const {listen}=window.__TAURI__.event;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let view=new URLSearchParams(location.search).get('view')||'waveform';
const labels={push:'押し出し・戻り',pulse:'丸めパルス',sine:'正弦波',triangle:'三角波'};
const clone=x=>structuredClone(x),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let project,draft,presets=[],selected=0,clipId=null,target='left',devices=[],pending=Promise.resolve(),dirty=false,drag=null;
function message(text,error=false){$('#message').textContent=text;$('#message').classList.toggle('aw-error',error);}
async function attempt(fn){try{return await fn()}catch(e){message(String(e),true);if(project&&view!=='waveform'){try{project=await invoke('get_project');if(view==='timeline')renderTimeline();else if(view==='settings')settings();}catch{}}return null}}
function enqueue(command,args){pending=pending.catch(()=>{}).then(()=>invoke(command,args));pending.catch(e=>message(String(e),true));return pending;}
function length(p){return p.kind==='push'?p.pushMs+p.returnMs:p.kind==='pulse'?p.widthMs:p.cycles*1000/p.frequency}
function duration(w){return Math.max(...w.parts.map(p=>p.startMs+length(p)))}
function value(p,time){const t=time-p.startMs,len=length(p);if(t<0||t>=len)return 0;let v;if(p.kind==='push')v=t<p.pushMs?Math.sin(Math.PI*t/p.pushMs)**2:-p.pushMs/p.returnMs*Math.sin(Math.PI*(t-p.pushMs)/p.returnMs)**2;else if(p.kind==='pulse')v=Math.sin(Math.PI*t/p.widthMs)**2;else{const phase=2*Math.PI*p.frequency*t/1000,edge=Math.min(2,len/4);v=p.kind==='triangle'?2/Math.PI*Math.asin(Math.sin(phase)):Math.sin(phase);v*=t<edge?.5-.5*Math.cos(Math.PI*t/edge):t>len-edge?.5-.5*Math.cos(Math.PI*(len-t)/edge):1;}return v*p.amplitude/100*p.polarity}
function sum(w,t,raw=false){return w.parts.reduce((v,p)=>v+value(p,t),0)*(raw?1:10**(w.levelDb/20))}
function path(w,width,height,span=duration(w),raw=false){let d='';for(let i=0;i<=800;i++){d+=(i?'L':'M')+(i/800*width).toFixed(2)+' '+(height/2-sum(w,i/800*span,raw)*height*.43).toFixed(2)}return d}
function mini(w){return `<svg viewBox="0 0 220 35" preserveAspectRatio="none" role="img" aria-label="${esc(w.name)}の波形"><path d="M0 17.5H220" stroke="var(--aw-line)"/><path d="${path(w,220,35,duration(w),true)}" fill="none" stroke="currentColor" stroke-width="1.3"/></svg>`}
function field(label,key,val,min,max,step,unit){return `<label>${label}<span class="aw-field"><input data-param="${key}" aria-label="${label}" type="number" value="${val}" min="${min}" max="${max}" step="${step}"><span>${unit}</span></span></label>`}
function check(w){if(!w.name.trim())throw Error('波形名を入力してください');if(w.parts.length>16)throw Error('部品は16個までです');for(const p of w.parts){if(!Number.isFinite(length(p))||p.startMs<0||p.startMs+length(p)>80.00001)throw Error('配置位置と波形の長さを80 ms以内にしてください');}return w}
function persistDraft(){check(draft);dirty=true;return enqueue('save_draft',{wave:clone(draft)}).then(p=>{project=p;dirty=false;message('自動保存済み');})}
function creation(){
 $('#app').innerHTML=`<div class="aw-toolbar aw-row aw-between"><div class="aw-row"><input id="wave-name" class="aw-name" aria-label="波形名" maxlength="120"><button id="new-wave">新規</button><select id="preset" aria-label="標準波形"><option value="">標準波形</option>${presets.map(w=>`<option value="${esc(w.id)}">${esc(w.name)}</option>`).join('')}</select></div><div class="aw-row"><button id="export">WAV書き出し</button><button id="save-wave" class="aw-primary">波形を保存</button></div></div><div class="aw-compose"><aside class="aw-parts"><div class="aw-caption">部品</div><div id="parts"></div><div class="aw-add"><select id="kind" aria-label="追加する部品">${Object.entries(labels).map(([id,n])=>`<option value="${id}">${n}</option>`).join('')}</select><button id="add-part">＋ 追加</button></div></aside><section class="aw-main"><div class="aw-row aw-between"><strong>合成波形</strong><span id="duration" class="aw-sub aw-num"></span></div><div class="aw-plot"><svg id="wave" preserveAspectRatio="none" role="img" aria-label="合成した駆動波形"></svg><div class="aw-axis">${[0,20,40,60,80].map(n=>`<span>${n}${n===80?' ms':''}</span>`).join('')}</div></div><div class="aw-row aw-between"><span id="peak" class="aw-sub"></span><span class="aw-sub">48 kHz</span></div><div class="aw-parameterhead aw-row aw-between"><strong id="part-name"></strong><button id="remove-part">部品を削除</button></div><div id="parameters" class="aw-parameters"></div></section></div><section class="aw-output"><div class="aw-adjustments"><div><div class="aw-row aw-between aw-levelhead"><label for="offset">配置位置</label><span><input id="offset-num" class="aw-levelnum" aria-label="配置位置 ms" type="number" min="0" step="0.1"> ms</span></div><input id="offset" type="range" aria-label="配置位置" min="0" step="0.1"><div class="aw-levelticks"><span>0 ms</span><span id="offset-max"></span></div></div><div><div class="aw-row aw-between aw-levelhead"><label for="level">出力レベル</label><span><input id="level-num" class="aw-levelnum" aria-label="出力レベル dB" type="number" min="-60" max="0" step="0.5"> dB</span></div><input id="level" type="range" aria-label="出力レベル" min="-60" max="0" step="0.5"><div class="aw-levelticks"><span>−60 dB</span><span>0 dB</span></div></div></div><div class="aw-playgroup"><div class="aw-row"><button id="play" class="aw-primary">▶ プレビュー</button><button id="stop">停止</button></div><span class="aw-sub">実測音圧は未校正</span></div></section>`;
 $('#wave-name').value=draft.name;
 $('#preset').onchange=()=>attempt(async()=>{const w=presets.find(w=>w.id===$('#preset').value);if(!w)return;draft=clone(w);selected=0;await persistDraft();creation();message('「'+draft.name+'」を読み込みました')});
 $('#wave-name').onchange=()=>attempt(async()=>{draft.name=$('#wave-name').value;await persistDraft()});
 $('#new-wave').onclick=()=>attempt(async()=>{draft={id:'draft',name:'パルス '+new Date().toLocaleTimeString('ja-JP'),levelDb:-18,parts:[newPart('push')]};selected=0;await persistDraft();creation();});
 $('#add-part').onclick=()=>attempt(async()=>{if(draft.parts.length>=16)throw Error('部品は16個までです');draft.parts.push(newPart($('#kind').value));selected=draft.parts.length-1;renderParts();plot();await persistDraft()});
 $('#remove-part').onclick=()=>attempt(async()=>{if(draft.parts.length===1)return;draft.parts.splice(selected,1);selected=Math.max(0,selected-1);renderParts();plot();await persistDraft()});
 $('#save-wave').onclick=()=>attempt(async()=>{check(draft);await pending;const w=clone(draft);if(!w.id.startsWith('user-'))w.id='user-'+crypto.randomUUID();project=await enqueue('save_wave',{wave:w});draft=clone(project.draft);message('「'+draft.name+'」を波形一覧に保存しました');});
 $('#export').onclick=()=>attempt(async()=>{check(draft);const p=await invoke('export_wav',{wave:clone(draft)});if(p)message('書き出しました: '+p)});
 $('#play').onclick=()=>attempt(async()=>{check(draft);await invoke('preview_wave',{wave:clone(draft)});message((await invoke('audio_status')).output||'プレビュー');});$('#stop').onclick=()=>attempt(()=>invoke('stop_audio'));
 for(const id of ['offset','offset-num']){$('#'+id).oninput=()=>{const p=draft.parts[selected],v=Number($('#'+id).value);if(!Number.isFinite(v)||v<0||v>80-length(p))return;p.startMs=v;plot();};$('#'+id).onchange=()=>attempt(persistDraft)}
 for(const id of ['level','level-num']){$('#'+id).oninput=()=>{const v=Number($('#'+id).value);if(!Number.isFinite(v)||v< -60||v>0)return;draft.levelDb=v;plot();attempt(()=>invoke('set_preview_level',{db:v}));};$('#'+id).onchange=()=>attempt(persistDraft)}
 renderParts();plot();
}
function newPart(kind){return {kind,startMs:0,amplitude:100,frequency:40,cycles:2,pushMs:12,returnMs:48,widthMs:20,polarity:1}}
function renderParts(){const p=draft.parts[selected];$('#parts').innerHTML=draft.parts.map((p,i)=>`<button class="aw-part" data-part="${i}" aria-pressed="${i===selected}"><strong>${labels[p.kind]}</strong><span>${String(i+1).padStart(2,'0')}</span></button>`).join('');$$('[data-part]').forEach(b=>b.onclick=()=>{selected=+b.dataset.part;renderParts();plot()});$('#part-name').textContent=labels[p.kind];$('#remove-part').disabled=draft.parts.length===1;
 let fields=p.kind==='push'?field('押し出し','pushMs',p.pushMs,1,79,.1,'ms')+field('戻り','returnMs',p.returnMs,1,79,.1,'ms'):p.kind==='pulse'?field('幅','widthMs',p.widthMs,1,80,.1,'ms'):field('周波数','frequency',p.frequency,1,200,1,'Hz')+field('周期数','cycles',p.cycles,.1,16,.1,'回');fields+=field('部品の振幅','amplitude',p.amplitude,0,100,1,'%')+`<label>極性<select data-param="polarity" aria-label="極性"><option value="1" ${p.polarity===1?'selected':''}>正</option><option value="-1" ${p.polarity===-1?'selected':''}>反転</option></select></label>`;$('#parameters').innerHTML=fields;
 $$('[data-param]').forEach(el=>el.onchange=()=>attempt(async()=>{const key=el.dataset.param,old=p[key];if(!el.checkValidity())throw Error('入力範囲を確認してください');p[key]=+el.value;try{check(draft)}catch(e){p[key]=old;el.value=old;throw e}plot();await persistDraft()}));
}
function plot(){if(view!=='waveform'||!$('#wave'))return;const svg=$('#wave'),width=Math.max(300,svg.clientWidth),h=210;svg.setAttribute('viewBox',`0 0 ${width} ${h}`);let grid='';for(let i=0;i<5;i++){grid+=`<path d="M28 ${15+i*45}H${width} M${28+i*(width-28)/4} 15V195" stroke="var(--aw-line)" stroke-width=".6"/>`;}svg.innerHTML=grid+'<text x="0" y="20" fill="var(--aw-sub)" font-size="11">+1</text><text x="8" y="109" fill="var(--aw-sub)" font-size="11">0</text><text x="0" y="199" fill="var(--aw-sub)" font-size="11">−1</text>'+`<path transform="translate(28,0)" d="${path(draft,width-28,h,80)}" fill="none" stroke="var(--aw-wave)" stroke-width="1.7"/>`;$('#duration').textContent=duration(draft).toFixed(1)+' / 80 ms';let peak=0;for(let i=0;i<3840;i++)peak=Math.max(peak,Math.abs(sum(draft,i/48)));$('#peak').textContent='ピーク '+(peak?(20*Math.log10(peak)).toFixed(1):'−∞')+' dBFS'+(peak>1?' · 上限超過':'');$('#peak').classList.toggle('aw-error',peak>1);$('#play').disabled=peak>1;const max=Math.max(0,Math.floor((80-length(draft.parts[selected]))*10)/10);for(const id of ['offset','offset-num']){$('#'+id).max=max;$('#'+id).value=draft.parts[selected].startMs}$('#offset-max').textContent=max+' ms';for(const id of ['level','level-num'])$('#'+id).value=draft.levelDb;}
function timeline(){
 $('#app').innerHTML=`<div class="aw-toolbar aw-row aw-between"><div class="aw-row"><button id="play" class="aw-primary">▶ 再生</button><button id="stop">停止</button><select id="timeline-target" aria-label="再生対象"><option value="all">すべて</option><option value="audio">オーディオのみ</option><option value="air">空気砲のみ</option></select><label>長さ <input id="span" aria-label="タイムラインの長さ" type="number" min="80" max="60000" step="10" style="width:84px"> ms</label></div><div class="aw-row"><button id="open-project">開く</button><button id="save-project">保存</button><button id="export">WAV書き出し</button><button id="export-unity">Unityへ書き出し</button></div></div><div class="aw-sequence"><section class="aw-sequencemain"><div id="ruler" class="aw-ruler"></div>${['left','right'].map(l=>`<div class="aw-track"><div class="aw-trackname">空気砲 ${l==='left'?'左':'右'}<div class="aw-sub" id="route-${l}"></div></div><div class="aw-lane" data-lane="${l}" aria-label="${l==='left'?'左':'右'}トラック"></div></div>`).join('')}<div class="aw-track"><div class="aw-trackname">オーディオ<div class="aw-sub" id="audio-route"></div></div><div class="aw-lane" id="audio-lane" aria-label="オーディオトラック"></div></div><div id="clip-edit" class="aw-clipedit"></div><p class="aw-hint">右の素材を対応するトラックへドラッグ</p></section><aside class="aw-waveforms"><div id="audio-library"></div><div class="aw-row aw-between"><strong>波形一覧</strong><div class="aw-row"><button data-target="left">左へ</button><button data-target="right">右へ</button></div></div><div id="wave-list" style="margin-top:18px"></div></aside></div>`;
 $('#play').onclick=()=>attempt(async()=>{await pending;await invoke('preview_timeline',{target:$('#timeline-target').value});message((await invoke('audio_status')).output||'タイムライン再生')});$('#stop').onclick=()=>attempt(()=>invoke('stop_audio'));
 $('#span').onchange=()=>attempt(async()=>{const old=project.durationMs;project.durationMs=+$('#span').value;try{await persistTimeline()}catch(e){project.durationMs=old;renderTimeline();throw e}renderTimeline()});
 $('#export-unity').onclick=()=>attempt(async()=>{await pending;const button=$('#export-unity');button.disabled=true;message('書き出し先のフォルダーを選択してください');try{const path=await invoke('export_unity');if(path){message('Unity用に書き出しました: '+path);const dialog=document.createElement('dialog');dialog.className='au-unity-dialog';dialog.innerHTML='<h2>Unityへの取り込み</h2><p>書き出した AirCueUnity フォルダーを、Unityの Assets へコピーしてください。</p><p>Sequence.aircueseq をシーンへドラッグすると、再生コンポーネント付きで配置できます。</p><p>初期設定ではイヤホン用の音声を再生します。4chの設定は同梱のREADMEを参照してください。</p><input aria-label=書き出し先 readonly><form method=dialog><button>閉じる</button></form>';dialog.querySelector('input').value=path;dialog.onclose=()=>dialog.remove();document.body.append(dialog);dialog.showModal()}else message('書き出しをキャンセルしました')}finally{button.disabled=false}});
 $('#open-project').onclick=()=>attempt(async()=>{await pending;const p=await invoke('project_file',{load:true});if(p){project=await invoke('get_project');audioSelectedClip=null;audioEditingClipId=null;audioHistoryReady=false;clipId=null;renderTimeline();message('読み込みました: '+p)}});
 $('#save-project').onclick=()=>attempt(async()=>{await pending;const p=await invoke('project_file',{load:false});if(p)message('保存しました: '+p)});
 $('#export').onclick=()=>attempt(async()=>{await pending;const p=await invoke('export_wav',{wave:null});if(p)message('書き出しました: '+p)});
 $$('[data-target]').forEach(b=>b.onclick=()=>{target=b.dataset.target;renderTimeline()});
 $$('[data-lane]').forEach(el=>{el.ondragover=e=>{e.preventDefault();e.dataTransfer.dropEffect='copy'};el.ondrop=e=>{e.preventDefault();attempt(async()=>{const data=JSON.parse(e.dataTransfer.getData('application/aircue')||'null');if(!data)return;const rect=el.getBoundingClientRect(),ms=Math.max(0,Math.round((e.clientX-rect.left)/rect.width*project.durationMs));if(data.clip){const c=project.clips.find(c=>c.id===data.clip);if(!c)return;const w=project.waves.find(w=>w.id===c.waveId);c.lane=el.dataset.lane;c.startMs=Math.min(ms,project.durationMs-duration(w));clipId=c.id;audioSelectedClip=null;await persistTimeline();renderTimeline();}else await place(data.wave,el.dataset.lane,ms);});};});
 renderTimeline();
}
async function persistTimeline(){const p=await enqueue('update_timeline',{clips:clone(project.clips),durationMs:project.durationMs});project=p;message('自動保存済み')}
async function place(id,lane=target,start=null){const w=project.waves.find(w=>w.id===id);if(!w)return;const existing=project.clips.filter(c=>c.lane===lane);const next=existing.reduce((end,c)=>Math.max(end,c.startMs+duration(project.waves.find(w=>w.id===c.waveId))+40),0);const ms=start===null?next:Math.min(start,project.durationMs-duration(w));if(ms+duration(w)>project.durationMs)throw Error('タイムラインの長さを延ばしてください');const c={id:crypto.randomUUID(),waveId:id,lane,startMs:ms,gainDb:0};project.clips.push(c);clipId=c.id;audioSelectedClip=null;await persistTimeline();renderTimeline();}
function renderTimeline(){if(view!=='timeline')return;$('#span').value=project.durationMs;$('#ruler').innerHTML=[0,1,2,3,4].map(n=>`<span>${Math.round(n*project.durationMs/4)}${n===4?' ms':''}</span>`).join('');$$('[data-target]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.target===target));for(const lane of ['left','right']){$('#route-'+lane).textContent=project.settings.routing[lane==='left'?2:3]+' ch';$(`[data-lane="${lane}"]`).innerHTML=project.clips.filter(c=>c.lane===lane).map(c=>{const w=project.waves.find(w=>w.id===c.waveId);return `<button class="aw-clip ${clipId===c.id?'aw-current':''}" draggable="true" data-clip="${esc(c.id)}" aria-label="${esc(w.name)} ${c.startMs} ms" title="${esc(w.name)} · ${c.startMs} ms" style="left:${c.startMs/project.durationMs*100}%;width:${duration(w)/project.durationMs*100}%">${mini(w)}</button>`}).join('')+'<div class="aw-playhead" hidden></div>';}
 $$('[data-clip]').forEach(b=>{b.onclick=()=>{clipId=b.dataset.clip;audioSelectedClip=null;renderTimeline()};b.ondragstart=e=>{e.dataTransfer.setData('application/aircue',JSON.stringify({clip:b.dataset.clip}));e.dataTransfer.effectAllowed='copyMove'}});
 const c=project.clips.find(c=>c.id===clipId),w=c&&project.waves.find(w=>w.id===c.waveId);$('#clip-edit').innerHTML=c?`<strong>${esc(w.name)}</strong><label>開始 <input id="clip-start" type="number" min="0" max="${project.durationMs-duration(w)}" step="0.1" value="${c.startMs}" aria-label="クリップ開始位置"> ms</label><label>レベル補正 <input id="clip-gain" type="number" min="-60" max="24" step=".5" value="${c.gainDb}" aria-label="クリップレベル補正"> dB</label><span class="aw-sub">合計 ${(w.levelDb+c.gainDb)>0?'+':''}${(w.levelDb+c.gainDb).toFixed(1)} dB</span><button id="duplicate">複製</button><button id="remove-clip">削除</button>`:'<span class="aw-sub">クリップ未選択</span>';
 if(c){for(const [id,key]of [['clip-start','startMs'],['clip-gain','gainDb']])$('#'+id).onchange=()=>attempt(async()=>{const el=$('#'+id),old=c[key];if(!el.checkValidity())throw Error('入力範囲を確認してください');c[key]=+el.value;try{await persistTimeline()}catch(e){c[key]=old;throw e}finally{renderTimeline()}});$('#remove-clip').onclick=()=>attempt(async()=>{project.clips=project.clips.filter(v=>v.id!==c.id);clipId=null;await persistTimeline();renderTimeline()});$('#duplicate').onclick=()=>attempt(()=>place(c.waveId,c.lane));}
 $('#wave-list').innerHTML=project.waves.map(w=>`<article class="aw-preset" draggable="true" data-wave="${esc(w.id)}"><div class="aw-row aw-between"><strong>${esc(w.name)}</strong><span class="aw-sub">${duration(w).toFixed(1)} ms</span></div>${mini(w)}<div class="aw-row aw-between"><button data-edit="${esc(w.id)}">編集</button><button data-place="${esc(w.id)}">配置</button></div></article>`).join('');$$('[data-wave]').forEach(el=>el.ondragstart=e=>{e.dataTransfer.setData('application/aircue',JSON.stringify({wave:el.dataset.wave}));e.dataTransfer.effectAllowed='copy'});$$('[data-place]').forEach(b=>b.onclick=()=>attempt(()=>place(b.dataset.place)));$$('[data-edit]').forEach(b=>b.onclick=()=>attempt(async()=>{await enqueue('save_draft',{wave:clone(project.waves.find(w=>w.id===b.dataset.edit))});await goView('waveform')}));
 renderAudioTimeline();
}
function settings(){const s=project.settings;$('#app').innerHTML=`<section class="aw-settings"><div class="settings-block"><div class="aw-row aw-between"><h2>出力機器</h2><button id="refresh-devices">更新</button></div><select id="device" class="device" aria-label="出力機器"><option value="">選択してください</option></select><p class="aw-sub">機器に合わせて再生形式を自動選択</p><div id="device-note" class="aw-sub"></div></div><div class="settings-block"><h2>チャンネル割り当て</h2><div class="aw-routes">${['イヤホン 左','イヤホン 右','空気砲 左','空気砲 右'].map((n,i)=>`<label>${n}<select data-route="${i}" aria-label="${n}">${[1,2,3,4].map(ch=>`<option value="${ch}" ${s.routing[i]===ch?'selected':''}>${ch} ch</option>`).join('')}</select></label>`).join('')}</div><label>波形プレビューの出力先 <select id="preview-lane" aria-label="波形プレビューの出力先"><option value="left">空気砲 左</option><option value="right">空気砲 右</option></select></label></div><div class="settings-block"><h2>設置</h2><div class="aw-routes">${['左','右'].map((n,i)=>`<label>出口から耳まで · ${n}<span><input data-distance="${i}" aria-label="出口から耳まで ${n}" type="number" min="1" max="300" value="${s.distanceCm[i]}" style="width:85px"> cm</span></label>`).join('')}</div><p class="aw-sub">出口径 20 mm · ND90-8 · AIYIMA A07</p><p class="aw-sub">距離は記録値です。出力への自動補正はありません。</p></div><p class="aw-sub">出力レベルはデジタルゲインです。実測音圧・風速の校正は未対応です。</p></section>`;
 $('#preview-lane').value=s.previewLane;$('#preview-lane').onchange=()=>attempt(async()=>{s.previewLane=$('#preview-lane').value;await persistSettings(s)});$$('[data-route]').forEach(el=>el.onchange=()=>attempt(async()=>{const i=+el.dataset.route,ch=+el.value,other=s.routing.indexOf(ch);s.routing[other]=s.routing[i];s.routing[i]=ch;await persistSettings(s);settings();renderDevices()}));$$('[data-distance]').forEach(el=>el.onchange=()=>attempt(async()=>{if(!el.checkValidity())throw Error('距離は1〜300 cmです');s.distanceCm[+el.dataset.distance]=+el.value;await persistSettings(s)}));$('#device').onchange=()=>attempt(async()=>{s.deviceId=$('#device').value||null;await persistSettings(s);renderDevices()});$('#refresh-devices').onclick=()=>attempt(refreshDevices);renderDevices();}
async function persistSettings(settings){project=await enqueue('update_settings',{settings:clone(settings)});message('出力設定を保存しました')}
function renderDevices(){
 if(!$('#device'))return;
 $('#device').innerHTML='<option value="">選択してください</option>'+devices.map(d=>`<option value="${esc(d.id)}">${esc(d.name)} · ${esc(d.host)} · ${d.channels?d.channels+' ch':'ch数未取得'}${d.usable?'':'（再生時に確認）'}</option>`).join('');
 $('#device').value=project.settings.deviceId||'';
 const selected=devices.find(d=>d.id===project.settings.deviceId);
 $('#device-note').textContent=!devices.length?'出力機器が見つかりません。接続後に更新してください。':
   project.settings.deviceId&&!selected?'選択した機器が見つかりません。接続後に更新するか、別の出力を選択してください。':
   selected&&selected.channels>0&&selected.channels<4?'互換再生：再生対象の左・右を機器のL/Rへ送ります。音声と空気砲は対象を切り替えて試聴できます。':
   '4chでは下の割り当てを使用します。音声と空気砲を同時に再生するときは4ch出力を使用します。';
}
async function refreshDevices(){$('#refresh-devices').disabled=true;message('出力機器を確認中…');try{devices=await invoke('list_devices');renderDevices();message('出力機器を更新しました')}finally{if($('#refresh-devices'))$('#refresh-devices').disabled=false}}
function renderView(){
 $('#title').textContent={waveform:'波形作成',audio:'オーディオ',timeline:'タイムライン',experiment:'実験',settings:'出力設定'}[view];
 $$('[data-window]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.window===view)));
 if(view==='waveform')creation();else if(view==='audio')audioEditor();else if(view==='timeline')timeline();else if(view==='experiment')experimentEditor();else{settings();attempt(refreshDevices)}
}
let switching=false;
async function goView(next){
 if(switching||!['waveform','audio','timeline','experiment','settings'].includes(next))return;
 switching=true;
 try{if(view==='audio')await flushAudioDraft();await pending;project=await invoke('get_project');draft=clone(project.draft);selected=Math.min(selected,draft.parts.length-1);view=next;history.replaceState(null,'','?view='+view);renderView();}
 finally{switching=false;}
}
async function boot(){
 [project,presets]=await Promise.all([invoke('get_project'),invoke('get_presets')]);draft=clone(project.draft);
 if(!['waveform','audio','timeline','experiment','settings'].includes(view))view='waveform';
 $$('[data-window]').forEach(b=>b.onclick=()=>attempt(()=>goView(b.dataset.window)));
 renderView();message('準備完了');const error=await invoke('startup_error');if(error)message(error,true);
 await listen('project-changed',({payload:p})=>{project=p;if(view==='timeline')renderTimeline();else if(view==='settings'){if(!document.activeElement?.matches('input,select')){settings();renderDevices()}}else if(view==='waveform'&&!dirty&&JSON.stringify(draft)!==JSON.stringify(p.draft)){draft=clone(p.draft);selected=Math.min(selected,draft.parts.length-1);creation()}});
 let lastError=null;setInterval(async()=>{try{const s=await invoke('audio_status');$('#play-status').textContent=s.playing?'再生中 · '+s.positionMs.toFixed(0)+' ms':'';if(s.error&&s.error!==lastError){message(s.error,true);lastError=s.error}if(view==='audio')drawAudioPosition(s.playing&&s.mode==='audio'?s.positionMs:null);if(view==='timeline')$$('.aw-playhead').forEach(el=>{el.hidden=!s.playing||s.mode!=='timeline';el.style.left=Math.min(100,s.positionMs/project.durationMs*100)+'%'});if(view==='experiment')await refreshExperiment();}catch{}},100);
 window.addEventListener('resize',plot);
}
boot().catch(e=>message('起動できませんでした: '+e,true));




