'use strict';
let audioDesign=null,audioEditingClipId=null,audioSelectedClip=null,audioRepeat=true,audioSaveTimer=null,audioRevision=0,audioSavedRevision=0,audioPreviewQueue=Promise.resolve(),audioImportBusy=false;
const audioNames={file:'音声ファイル',sine:'正弦波',triangle:'三角波',square:'矩形波',noise:'ホワイトノイズ',sweep:'周波数スイープ'};
function audioName(d){return d.source==='file'?(project.audioAssets.find(a=>a.id===d.assetId)?.name||'音声'):audioNames[d.source]+(['sine','triangle','square'].includes(d.source)?' '+d.frequency+' Hz':'')}
function audioRange(label,key,value,min,max,step,unit){return `<label class="au-range"><span>${label}<span><input type="number" data-audio-param="${key}" aria-label="${label} ${unit}" value="${value}" min="${min}" max="${max}" step="${step}"> ${unit}</span></span><input type="range" data-audio-param="${key}" aria-label="${label}" value="${value}" min="${min}" max="${max}" step="${step}"></label>`}
function audioField(label,key,value,min,max,step,unit){return `<label>${label}<span class="aw-field"><input type="number" data-audio-param="${key}" aria-label="${label}" value="${value}" min="${min}" max="${max}" step="${step}">${unit}</span></label>`}
function audioEditor(){
 audioDesign=clone(project.audioDraft);audioSavedRevision=audioRevision;
 const d=audioDesign,a=project.audioAssets.find(a=>a.id===d.assetId);
 $('#app').innerHTML=`<div class="aw-toolbar aw-row aw-between"><div class="aw-row"><button id="audio-import">音声を読み込む</button><span class="aw-sub">WAV・MP3・FLAC・OGG・M4A</span></div><div class="aw-row"><button id="audio-export">WAV書き出し</button>${audioEditingClipId?'<button id="audio-update">クリップを更新</button>':''}<button id="audio-place" class="aw-primary">タイムラインに配置</button></div></div><div class="au-editor"><aside class="au-source"><div class="aw-caption">音源</div><select id="audio-source" aria-label="音源の種類">${Object.entries(audioNames).map(([key,name])=>`<option value="${key}" ${d.source===key?'selected':''}>${name}</option>`).join('')}</select>${d.source==='file'?`<select id="audio-asset" aria-label="音声素材"><option value="">ファイルを選択</option>${project.audioAssets.map(a=>`<option value="${esc(a.id)}" ${a.id===d.assetId?'selected':''}>${esc(a.name)}</option>`).join('')}</select><div class="aw-sub">${a?(a.frames/48000).toFixed(2)+' s · '+a.sourceChannels+' ch'+(a.sourceChannels>2?' · 先頭2chを使用':''):''}</div>`:''}<div class="au-wave"><svg id="audio-wave" viewBox="0 0 300 70" preserveAspectRatio="none" role="img" aria-label="音源波形"></svg></div><div class="au-fields">${d.source==='file'?audioField('素材の開始位置','offsetMs',d.offsetMs,0,a?Math.max(0,a.frames/48-20):600000,'any','ms'):d.source==='noise'?'':audioRange('周波数','frequency',d.frequency,20,16000,1,'Hz')}${d.source==='sweep'?audioRange('終点周波数','endFrequency',d.endFrequency,20,16000,1,'Hz'):''}${audioField('再生時間','durationMs',d.durationMs,20,a&&d.source==='file'?Math.min(60000,a.frames/48-d.offsetMs):60000,'any','ms')}</div>${audioRange('音声レベル','levelDb',d.levelDb,-60,12,.5,'dB')}<div class="au-presets"><span class="aw-sub">テスト音</span><div class="aw-row"><button data-tone="440">440 Hz</button><button data-tone="1000">1 kHz</button><button data-tone="noise">ノイズ</button></div></div><div class="au-transport"><div class="aw-row"><button id="audio-play" class="aw-primary">▶ プレビュー</button><button id="audio-stop">停止</button></div><label><input id="audio-repeat" type="checkbox" ${audioRepeat?'checked':''}> 繰り返し</label><div class="aw-sub">イヤホン ${project.settings.routing[0]}・${project.settings.routing[1]} ch</div></div></aside>${spatialEditorMarkup(d)}</div>`;
 $('#audio-import').onclick=()=>attempt(importAudioFile);$('#audio-export').onclick=()=>attempt(async()=>{await flushAudioDraft();const file=await invoke('export_audio',{design:clone(audioDesign)});if(file)message('書き出しました: '+file)});
 $('#audio-place').onclick=()=>attempt(async()=>{await flushAudioDraft();await addAudioClip(clone(audioDesign));await goView('timeline')});
 if($('#audio-update'))$('#audio-update').onclick=()=>attempt(async()=>{await flushAudioDraft();const c=project.audioClips.find(c=>c.id===audioEditingClipId);if(!c)throw Error('更新するクリップがありません');c.design=clone(audioDesign);c.name=audioName(audioDesign);project.durationMs=Math.max(project.durationMs,c.startMs+c.design.durationMs);await persistAudioTimeline();await goView('timeline')});
 $('#audio-source').onchange=()=>attempt(async()=>{const key=$('#audio-source').value;if(key==='file'&&!project.audioAssets.length){await importAudioFile();if(!project.audioAssets.length)audioEditor();return;}audioDesign.source=key;if(key==='file'){const asset=project.audioAssets.find(a=>a.id===audioDesign.assetId)||project.audioAssets[0];audioDesign.assetId=asset.id;audioDesign.offsetMs=0;audioDesign.durationMs=Math.min(10000,asset.frames/48);}audioRevision++;await flushAudioDraft();audioEditor()});
 if($('#audio-asset'))$('#audio-asset').onchange=()=>attempt(async()=>{const asset=project.audioAssets.find(a=>a.id===$('#audio-asset').value);if(!asset)return;audioDesign.assetId=asset.id;audioDesign.offsetMs=0;audioDesign.durationMs=Math.min(10000,asset.frames/48);audioRevision++;await flushAudioDraft();audioEditor()});
 $$('[data-audio-param]').forEach(el=>el.oninput=()=>{if(el.value===''||!el.checkValidity())return;const key=el.dataset.audioParam;setAudioParameter(key,Number(el.value));$$(`[data-audio-param="${key}"]`).forEach(other=>{if(other!==el)other.value=el.value});queueAudioEdit();drawAudioPosition();drawAudioWave();});
 $('#audio-repeat').onchange=()=>attempt(async()=>{audioRepeat=$('#audio-repeat').checked;await invoke('set_audio_loop',{looping:audioRepeat})});
 $('#audio-play').onclick=()=>attempt(async()=>{await flushAudioDraft();await invoke('preview_audio',{design:clone(audioDesign),looping:audioRepeat});message((await invoke('audio_status')).output)});$('#audio-stop').onclick=()=>attempt(()=>invoke('stop_audio'));
 $$('[data-tone]').forEach(b=>b.onclick=()=>attempt(async()=>{audioDesign.source=b.dataset.tone==='noise'?'noise':'sine';if(b.dataset.tone!=='noise')audioDesign.frequency=+b.dataset.tone;audioDesign.durationMs=3000;audioRevision++;await flushAudioDraft();audioEditor()}));
 bindSpatialEditor();drawAudioWave();drawAudioPosition();
}
function queueAudioEdit(){audioRevision++;clearTimeout(audioSaveTimer);audioSaveTimer=setTimeout(()=>attempt(flushAudioDraft),180)}
async function flushAudioDraft(){clearTimeout(audioSaveTimer);if(!audioDesign||audioRevision===audioSavedRevision)return;const revision=audioRevision,snapshot=clone(audioDesign);const p=await enqueue('save_audio_draft',{design:snapshot});project=p;audioSavedRevision=revision;message('オーディオ設定を保存しました');audioPreviewQueue=audioPreviewQueue.catch(()=>{}).then(async()=>{if(revision!==audioRevision)return;await invoke('update_audio_preview',{design:snapshot})});audioPreviewQueue.catch(e=>message(String(e),true));}
async function importAudioFile(){if(audioImportBusy)return;audioImportBusy=true;try{await flushAudioDraft();message('音声ファイルを選択してください');const p=await invoke('import_audio');if(p){project=p;audioEditingClipId=null;audioRevision=audioSavedRevision=0;await goView('audio');message('読み込みました: '+audioName(project.audioDraft));}}finally{audioImportBusy=false}}
function audioMini(design,width=300,height=70){const asset=project.audioAssets.find(a=>a.id===design.assetId);let vals=[];if(design.source==='file'&&asset){const n=asset.peaks.length,start=Math.floor(design.offsetMs/(asset.frames/48)*n),end=Math.max(start+1,Math.ceil((design.offsetMs+design.durationMs)/(asset.frames/48)*n));vals=asset.peaks.slice(start,end);let shape='';vals.forEach((v,i)=>{const x=i/Math.max(1,vals.length-1)*width;shape+=`M${x.toFixed(1)} ${(height/2-Math.min(v,1)*height*.45).toFixed(1)}V${(height/2+Math.min(v,1)*height*.45).toFixed(1)}`});return `<path d="${shape}" stroke="currentColor" stroke-width="1"/>`;}let shape='';for(let i=0;i<=300;i++){const phase=i/300*Math.PI*8;const value=design.source==='noise'?Math.sin(i*7.83)*Math.cos(i*3.37):design.source==='triangle'?2/Math.PI*Math.asin(Math.sin(phase)):design.source==='square'?Math.sign(Math.sin(phase)):Math.sin(phase);shape+=(i?'L':'M')+(i/300*width).toFixed(1)+' '+(height/2-value*height*.4).toFixed(1)}return `<path d="${shape}" fill="none" stroke="currentColor" stroke-width="1.2"/>`}
function drawAudioWave(){if($('#audio-wave')&&audioDesign)$('#audio-wave').innerHTML=audioMini(audioDesign)}
async function persistAudioTimeline(){project=await enqueue('update_audio_timeline',{clips:clone(project.audioClips),durationMs:project.durationMs});message('自動保存済み')}
async function addAudioClip(design,start=null){const at=start??project.audioClips.reduce((end,c)=>Math.max(end,c.startMs+c.design.durationMs),0);const end=at+design.durationMs;if(end>60000)throw Error('音声が60秒の終端を超えます。再生範囲を短くしてください');project.durationMs=Math.max(project.durationMs,end);const clip={id:crypto.randomUUID(),name:audioName(design),startMs:at,gainDb:0,design:clone(design)};project.audioClips.push(clip);audioSelectedClip=clip.id;clipId=null;await persistAudioTimeline();if(view==='timeline')renderTimeline()}
function renderAudioTimeline(){if(view!=='timeline'||!$('#audio-lane'))return;$('#audio-route').textContent=project.settings.routing[0]+'・'+project.settings.routing[1]+' ch';$('#audio-lane').innerHTML=project.audioClips.map(c=>`<button class="aw-clip ${audioSelectedClip===c.id?'aw-current':''}" draggable="true" data-audio-clip="${esc(c.id)}" aria-label="${esc(c.name)} ${c.startMs} ms" title="${esc(c.name)} · ${c.startMs} ms" style="left:${c.startMs/project.durationMs*100}%;width:${c.design.durationMs/project.durationMs*100}%"><span>${esc(c.name)}</span><svg viewBox="0 0 300 40" preserveAspectRatio="none">${audioMini(c.design,300,40)}</svg></button>`).join('')+'<div class="aw-playhead" hidden></div>';
 $$('[data-audio-clip]').forEach(b=>{b.onclick=()=>{audioSelectedClip=b.dataset.audioClip;clipId=null;renderTimeline()};b.ondragstart=e=>{e.dataTransfer.setData('application/aircue-audio',JSON.stringify({clip:b.dataset.audioClip}));e.dataTransfer.effectAllowed='move'}});
 const c=project.audioClips.find(c=>c.id===audioSelectedClip);if(c){$('#clip-edit').innerHTML=`<strong>${esc(c.name)}</strong><label>開始<input id="audio-clip-start" aria-label="音声クリップ開始位置" type="number" min="0" max="${60000-c.design.durationMs}" value="${c.startMs}">ms</label><label>レベル補正<input id="audio-clip-gain" aria-label="音声クリップレベル補正" type="number" min="-60" max="24" step=".5" value="${c.gainDb}">dB</label><label><input id="audio-clip-spatial" type="checkbox" ${c.design.spatial?'checked':''}>立体音響</label><button id="audio-clip-edit">音源・位置を編集</button><button id="audio-clip-duplicate">複製</button><button id="audio-clip-remove">削除</button>`;for(const [id,key]of [['audio-clip-start','startMs'],['audio-clip-gain','gainDb']])$('#'+id).onchange=()=>attempt(async()=>{const el=$('#'+id);if(!el.checkValidity())throw Error('入力範囲を確認してください');c[key]=+el.value;project.durationMs=Math.max(project.durationMs,c.startMs+c.design.durationMs);await persistAudioTimeline();renderTimeline()});$('#audio-clip-spatial').onchange=()=>attempt(async()=>{c.design.spatial=$('#audio-clip-spatial').checked;await persistAudioTimeline();renderTimeline()});$('#audio-clip-edit').onclick=()=>attempt(async()=>{await enqueue('save_audio_draft',{design:clone(c.design)});audioEditingClipId=c.id;audioRevision=audioSavedRevision=0;await goView('audio')});$('#audio-clip-duplicate').onclick=()=>attempt(async()=>{const start=c.startMs+c.design.durationMs;if(start+c.design.durationMs>60000)throw Error('複製先が60秒の終端を超えます');const copy={...clone(c),id:crypto.randomUUID(),startMs:start};project.audioClips.push(copy);project.durationMs=Math.max(project.durationMs,start+c.design.durationMs);audioSelectedClip=copy.id;await persistAudioTimeline();renderTimeline()});$('#audio-clip-remove').onclick=()=>attempt(async()=>{project.audioClips=project.audioClips.filter(x=>x.id!==c.id);audioSelectedClip=null;await persistAudioTimeline();renderTimeline()});}
 const lane=$('#audio-lane');lane.ondragover=e=>e.preventDefault();lane.ondrop=e=>{e.preventDefault();attempt(async()=>{const data=JSON.parse(e.dataTransfer.getData('application/aircue-audio')||'null');if(!data)return;const rect=lane.getBoundingClientRect();let start=Math.max(0,Math.round((e.clientX-rect.left)/rect.width*project.durationMs));if(data.clip){const c=project.audioClips.find(c=>c.id===data.clip);c.startMs=Math.min(start,60000-c.design.durationMs);project.durationMs=Math.max(project.durationMs,c.startMs+c.design.durationMs);await persistAudioTimeline();renderTimeline();}else{const asset=project.audioAssets.find(a=>a.id===data.asset);if(asset)await addAudioClip(designFromAsset(asset),start);}})};
 $('#audio-library').innerHTML=`<div class="aw-row aw-between"><strong>音声素材</strong><button id="timeline-import">読み込む</button></div>${project.audioAssets.length?project.audioAssets.map(a=>`<article class="aw-preset" draggable="true" data-audio-asset="${esc(a.id)}"><strong>${esc(a.name)}</strong><div class="aw-sub">${(a.frames/48000).toFixed(2)} s</div><div class="aw-row"><button data-open-audio="${esc(a.id)}">編集</button><button data-place-audio="${esc(a.id)}">配置</button></div></article>`).join(''):'<p class="aw-sub">音声ファイル未追加</p>'}<div class="aw-rule"></div><strong>空気砲の波形</strong>`;$('#timeline-import').onclick=()=>attempt(importAudioFile);$$('[data-audio-asset]').forEach(el=>el.ondragstart=e=>{e.dataTransfer.setData('application/aircue-audio',JSON.stringify({asset:el.dataset.audioAsset}));e.dataTransfer.effectAllowed='copy'});$$('[data-open-audio]').forEach(b=>b.onclick=()=>attempt(async()=>{const asset=project.audioAssets.find(a=>a.id===b.dataset.openAudio);await enqueue('save_audio_draft',{design:designFromAsset(asset)});audioEditingClipId=null;audioRevision=audioSavedRevision=0;await goView('audio')}));$$('[data-place-audio]').forEach(b=>b.onclick=()=>attempt(()=>addAudioClip(designFromAsset(project.audioAssets.find(a=>a.id===b.dataset.placeAudio)))));
}
function designFromAsset(a){return {...clone(project.audioDraft),source:'file',assetId:a.id,offsetMs:0,durationMs:Math.min(10000,a.frames/48),levelDb:-18,spatial:false,motion:'fixed'}}
